name: Get Currently Deployed Ref
description: 'Get the ref which is currently deployed in the supplied environment'
author: Kyle Bjordahl
inputs:
  environment: 
    required: true
    description: 'The environment to check for the latest deployment'
  token: 
    required: true
    description: 'GitHub token with read access to deployment and statuses'
outputs:
  ref:
    description: The git ref associated with the latest successful deployment to the environment
  sha:
    description: The full git sha (Object ID) associated with the latest successful deployment to the environment

runs:
  using: 'node20'
  main: 'dist/index.js'
