name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  # make a fake deploy to detect
  fake-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo ${{ github.ref }}

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: 
      - fake-deploy
    permissions:
      deployments: read
      statuses: read
    steps:
      - uses: actions/checkout@v3
      - id: test_action
        uses: ./
        with:
          environment: test
          token: ${{ github.token }}
      - name: Check output of the action
        # the output should match the ref of the running action, since the last deploy was created from this workflow
        run: |
          [ "${{ steps.test_action.outputs.ref }}" = "${{ github.ref_name }}" ]

