name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  NODE_OPTIONS: --openssl-legacy-provider

concurrency:
  cancel-in-progress: false
  group: test

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  # make a fake deploy to detect
  fake-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo ${{ github.ref }}

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs:
      - fake-deploy
    permissions:
      deployments: read
      statuses: read
    steps:
      - uses: actions/checkout@v4
      - id: test_action
        uses: ./
        with:
          environment: test
          token: ${{ github.token }}

      - name: Debug test outputs
        run: echo "${{ toJson(steps.test_action.outputs) }}"

      - name: Check output of the action
        # the output should match the ref of the running action, since the last deploy was created from this workflow
        run: |
          [ "${{ steps.test_action.outputs.ref }}" = "${{ github.head_ref || github.ref_name }}" ] && [ "${{ steps.test_action.outputs.sha }}" = "${{ github.event.pull_request.head.sha || github.event.after }}" ]
